//==============================================================================
// i2c_driver.sv
//
// Drives the I2C bus as the target/slave device that the DUT (the only
// I2C master, per confirmed no-multi-controller spec) talks to.
//
// NOTE ON TIMING: bit-level sampling here uses direct edge waits on the
// physical bus (@(posedge vif.scl) etc.) rather than a UVM clocking block,
// since SCL is generated by the DUT and is asynchronous to the testbench.
// The clock-stretch hold duration (do_clock_stretch) and the SDA-stuck
// hold duration are placeholder delays (#ns) marked TUNE - these need to
// be calibrated against real DUT waveforms once simulation is available,
// they are not derived from a spec-given numeric value.
//==============================================================================
`ifndef I2C_DRIVER_SV
`define I2C_DRIVER_SV

class i2c_driver extends uvm_driver #(i2c_transaction);
  `uvm_component_utils(i2c_driver)

  virtual i2c_if vif;
  i2c_config     cfg;

  function new(string name = "i2c_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(i2c_config)::get(this, "", "i2c_config", cfg))
      `uvm_fatal("NOCFG", "i2c_config not found in config_db")
    vif = cfg.vif;
  endfunction

  virtual task run_phase(uvm_phase phase);
    i2c_transaction req;
    vif.agt_release_all();
    forever begin
      seq_item_port.get_next_item(req);
      handle_transaction(req);
      seq_item_port.item_done();
    end
  endtask

  //----------------------------------------------------------------------
  // Bus primitives
  //----------------------------------------------------------------------

  task automatic wait_for_start();
    forever begin
      @(negedge vif.sda);
      if (vif.scl === 1'b1) break;
    end
  endtask

  task automatic wait_for_stop();
    forever begin
      @(posedge vif.sda);
      if (vif.scl === 1'b1) break;
    end
  endtask

  task automatic wait_for_stop_or_repeated_start(bit expect_repeat_start);
    if (expect_repeat_start) wait_for_start();
    else                     wait_for_stop();
  endtask

  task automatic sample_byte(output bit [7:0] byte_val);
    for (int i = 7; i >= 0; i--) begin
      @(posedge vif.scl);
      byte_val[i] = vif.sda;
    end
  endtask

  task automatic send_ack(bit ack); // ack=1 -> pull SDA low (ACK); ack=0 -> release (NACK)
    @(negedge vif.scl);
    if (ack) vif.agt_drive_sda(1'b0);
    else     vif.agt_release_sda();
    @(posedge vif.scl);
    @(negedge vif.scl);
    vif.agt_release_sda();
  endtask

  task automatic wait_for_ack(output bit ack_is_ack);
    @(posedge vif.scl);
    ack_is_ack = (vif.sda === 1'b0);
    @(negedge vif.scl);
  endtask

  task automatic drive_byte(bit [7:0] data);
    for (int i = 7; i >= 0; i--) begin
      if (data[i]) vif.agt_release_sda();
      else         vif.agt_drive_sda(1'b0);
      @(posedge vif.scl);
      @(negedge vif.scl);
    end
    vif.agt_release_sda(); // release before master drives ACK/NACK
  endtask

  task automatic do_clock_stretch(int cycles);
    @(negedge vif.scl);
    vif.agt_stretch_scl();
    #(cycles * 10); // TUNE: placeholder hold duration, calibrate against sim
    vif.agt_release_scl();
  endtask

  //----------------------------------------------------------------------
  // Top-level transaction handling
  //----------------------------------------------------------------------
  task automatic handle_transaction(i2c_transaction req);
    bit [7:0] addr_byte;
    bit       rw_bit;
    bit       ack;

    vif.agt_release_all();
    wait_for_start();
    sample_byte(addr_byte);
    rw_bit = addr_byte[0];

    send_ack(!req.inject_addr_nack);
    req.addr_ack_rcvd = !req.inject_addr_nack;

    if (req.inject_addr_nack) begin
      wait_for_stop();
      vif.agt_release_all();
      return;
    end

    if (rw_bit == 1'b0) begin
      // I2C_WRITE: DUT (master) sends data, this agent (slave) receives + ACKs
      for (int b = 0; b < req.num_bytes; b++) begin
        bit [7:0] data_byte;
        if (req.inject_clock_stretch && b == 0) do_clock_stretch(req.stretch_cycles);
        sample_byte(data_byte);
        req.rd_data[b] = data_byte;
        ack = !(req.inject_data_nack_on && (b == req.data_nack_byte_idx));
        send_ack(ack);
        req.data_ack_rcvd[b] = ack;
        if (!ack) break;
      end
    end else begin
      // I2C_READ: DUT (master) reads, this agent (slave) drives data bytes
      for (int b = 0; b < req.num_bytes; b++) begin
        bit ack_from_master;
        if (req.inject_clock_stretch && b == 0) do_clock_stretch(req.stretch_cycles);
        drive_byte(req.wr_data[b]);
        wait_for_ack(ack_from_master);
        req.data_ack_rcvd[b] = ack_from_master;
        if (!ack_from_master) break; // master NACKing last byte is normal termination
      end
    end

    if (req.inject_sda_stuck_after_stop) begin
      wait_for_stop();
      vif.agt_drive_sda(1'b0); // deliberately hold SDA low across STOP to trigger sda_err
      #200; // TUNE: hold duration, calibrate once sda_err sample window confirmed in sim
      vif.agt_release_sda();
    end else begin
      wait_for_stop_or_repeated_start(req.repeat_start);
    end

    vif.agt_release_all();
  endtask

endclass

`endif // I2C_DRIVER_SV
